apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t1ge4hb83-nodejs 
  janus-idp.io/tekton: t1ge4hb83-nodejs
  backstage.io/kubernetes-id: t1ge4hb83-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t1ge4hb83-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml